spring.application.name=FundTransferApplication
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fund_transfer
spring.datasource.username=root
spring.datasource.password=kiran
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


